### ISSUE TITLE
Order of resolution of references - resolve remotes first?

### ISSUE THREAD

**Issue by mrchief** [BigstickCarpet/swagger-parser#50] opened 2016-09-21 14:36 UTC
Given this folder structure:

```
|   index.yaml
|   parameters.yaml
|   responses.yaml
|   
+---definitions
|   |   index.yaml
|   |   
|   +---error
|   |       error_model.yaml
|   |       extended_error_model.yaml
|               
\---paths
    |   index.yaml
```
Consider this yaml:

**index.yaml**

```yaml
swagger: '2.0'

info:
  version: 1.0.0
  title: User API
  description: User specific API

schemes:
  - http
  - https

produces:
  - application/json
  - text/json

paths:
  $ref: ./paths/index.yaml

definitions:
  $ref: ./definitions/index.yaml

parameters:
  $ref: ./parameters.yaml

responses:
  $ref: ./responses.yaml
```

**responses.yaml**
```yaml
# Common responses
200:
  description: OK
  schema:
    type: string

DefaultError:
  description: Error payload
  schema:
    $ref: '#/definitions/ExtendedErrorModel'
```

**extended_error_model.yaml**
```yaml
allOf:
- $ref: '#/definitions/ErrorModel'
- type: object
  properties:
    detail:
      type: string
    meta:
      type: string
```

**error_model.yaml**
```yaml
type: object
required:
  - status
  - code
  - title
properties:
  code:
    type: integer
  title:
    type: string
  status:
    type: integer
    minimum: 100
    maximum: 600
```

`SwaggerParser.validate('index.yaml')` fails because `'#/definitions/ExtendedErrorModel'` doesn't exist inside **responses.yaml**. However, if I use [json-refs](https://github.com/whitlockjc/json-refs) and [js-yaml](https://github.com/nodeca/js-yaml) to load and parse the YAML, the resolution works.

I believe this is because json-refs first resolves all remote refs, then proceeds with local ones.

I'm not sure if the spec (OAI or json ref) dictates one way or the other. So I'm not sure if this is an issue or not. 

Could you please shed some light on this?

**Comment by BigstickCarpet** [comment] 2016-10-06 11:59
Hi.  Sorry for not replying sooner.  I've been away on holiday.

The `$ref` in `responses.yaml` is invalid, because it's pointing to a definition _within the same file_, which doesn't exist (see the [JSON Reference spec](https://tools.ietf.org/html/draft-pbryan-zyp-json-ref-03) for details).

Instead of referencing a type definition, you need to directly reference the `extended_error_model.yaml` file instead, like this:

```yaml
# Common responses
200:
  description: OK
  schema:
    type: string

DefaultError:
  description: Error payload
  schema:
    $ref: 'definitions/error/extended_error_model.yaml'     # <-- referencing the file
```

**Comment by BigstickCarpet** [comment] 2016-10-06 12:09
Another way to fix the problem would be to point to the type definition in your `index.yaml` or `definitions/index.yaml` file, like this:

```yaml
# Common responses
200:
  description: OK
  schema:
    type: string

DefaultError:
  description: Error payload
  schema:
    $ref: 'index.yaml#/definitions/ExtendedErrorModel'     # <-- referencing the type definition
```

**Comment by mrchief** [comment] 2016-10-06 15:42
Thanks for pointing to the spec. 

I couldn't find anything definitive and the closest I found indicated that this is tooling issue. [sway](https://github.com/apigee-127/sway) and its predecessor [swagger-tools](https://github.com/apigee-127/swagger-tools) seem to do it the other way (remotes first and then local). 

So I wasn't sure which way is the right way. @whitlockjc If this is invalid per spec, why Sway and swagger-tool support it?

**Comment by whitlockjc** [comment] 2016-10-06 16:04
When I read the spec, I didn't feel it was very clear.  I am sure the point where you suggest I deviate from the spec falls in this statement:

    If a URI contains a fragment identifier, then the fragment should be
    resolved per the fragment resolution mechansim of the referrant
    document.

While this does explain that local references should be resolved against the local document, the specification leaves a lot to interpretation when it comes to the order in which resolution happens.  It's this that I think causes the discrepancy.  I'll file a bug in [json-refs](https://github.com/whitlockjc/json-refs) and reference this issue in the report.  I'm currently rewriting json-refs anyways and we'll just not do the hierarchical resolution for local references in remote documents.  Thanks for bringing this up.

**Comment by BigstickCarpet** [comment] 2016-10-06 16:08
@mrchief - Just to clarify... It's not a matter of "remotes first" vs "local first".  The order is irrelevant.  The issue is scope resolution.  A `$ref` such as `#/foo/bar` is relative to the root of the _current_ file, not to the root of the entire JSON schema.  That said, the JSON Reference spec _does_ allow the resolution scope to be changed using special `id` properties, but I don't think that feature of JSON Reference is supported by Swagger.

**Comment by whitlockjc** [comment] 2016-10-06 16:18
Well, what I meant by order was if you just create a composite document by _including_ the remote document first and _then_ resolving the local references, the local reference in your remote document could possibly apply to the original _(remote)_ document _or_ the composite document that the remote document was just included into.  In fact, that's why it was written the way it was.  In all fairness, I do think there was some invalid Swagger usage that led to this.

**Comment by BigstickCarpet** [comment] 2016-10-06 16:26
@whitlockjc - Ah, ok.  I see what you mean by "order" now.  Thanks for the clarification. 👍

**Comment by whitlockjc** [comment] 2016-10-06 16:31
No problem.  The good news is this _feature_ was a pain to implement anyways so removing it makes my life easier. 👍

**Comment by BigstickCarpet** [comment] 2016-10-19 11:38
Closing this issue, since Swagger Parser is working as intended.

**Closed by BigstickCarpet** 2016-10-19 11:38 UTC
